In [4]:
my_list=[1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


## importing numpy package

In [5]:
import numpy as np

In [6]:
array= np.array(my_list,dtype=int)
print(array)

[1 2 3 4 5 6]


In [7]:
print(type(array))

<class 'numpy.ndarray'>


In [8]:
print(len(array))

6


In [9]:
print(array.ndim)

1


In [10]:
print(array.shape)

(6,)


In [11]:
array=array.reshape(3,2)
print(array)
array.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [12]:
array3= array.reshape(3,-1)
print(array3)
print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [13]:
my_list2=[1,2,3,4,5]
my_list3=[2,3,4,5,6]
my_list4=[9,7,6,8,9]
mul_arr=np.array([my_list2,my_list3,my_list4])
print(mul_arr)
print(mul_arr.shape)       #shape is no of rows and columns--->(3,5)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [14]:
mul_arr.reshape(1,15)  # array value in single row with a 15 columns

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

# NumPy- Attributes 

In [15]:
a= np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [16]:
r= range(24)
print(r)

range(0, 24)


In [17]:
# array of evenly spaced numbers
a=np.arange(24)       
print(a)
print(a.ndim)   # single dimension  array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [18]:
# reshaping  array
b= a.reshape(6,4,1)
print(b)
# here 6 is no of vectors (groups of elements)
# 4 is no of elements each vector has and
# 1 is the no of elements each sub-vector or [] has(increment) 

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


# Numpy Arthimetic operations


In [19]:
x= np.array([[1,2],[3,4]], dtype=np.float64) 
y= np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [20]:
# ADDITION
print(x+y)


[[ 6.  8.]
 [10. 12.]]


In [21]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [24]:
# Substract
print( x- y)


[[-4. -4.]
 [-4. -4.]]


In [25]:
# multiply()
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [26]:
print(x.dot(y))

[[19. 22.]
 [43. 50.]]


In [27]:
# divide
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
