In [1]:
import numpy as np

In [2]:
data= np.array([5,7,8,2,3,9,0])
data

array([5, 7, 8, 2, 3, 9, 0])

In [3]:
type(data)

numpy.ndarray

In [4]:
data.shape

(7,)

In [5]:
data[3]=7  # to replace the indexed element in []

In [6]:
data   # 3rd element is replaced

array([5, 7, 8, 7, 3, 9, 0])

In [7]:
data= np.array([5,7,8.6,2,3,9,0])     # all elements converted to float from int
data

array([5. , 7. , 8.6, 2. , 3. , 9. , 0. ])

In [9]:
data[0]

5.0

In [10]:
data= np.array([5,7,'h',2,3,9,0])   #U11 is for string
data

array(['5', '7', 'h', '2', '3', '9', '0'], dtype='<U11')

In [12]:
data= np.array([5,7,True,2,3,9,0])

In [13]:
data     # True is 1 and 

array([5, 7, 1, 2, 3, 9, 0])

In [14]:
data.max()

9

#  NUMPY  METHODS


In [15]:
np.arange(1,11)   # Array from 1 till 10 (less than 11){<11}

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.linspace(1,9,10)    # these are linearly spaced array whose differences are same

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])