In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.decomposition import PCA

In [3]:
X= np.array([
         [-1,-1],
        [-2,-1],
         [-3,-2],
         [1,1],
         [2,1],
         [3,2]
])

In [10]:
pca= PCA(n_components=1)

In [11]:
pca.fit(X)

PCA(n_components=1)

In [12]:
# explained
pca.explained_variance_

array([7.93954312])

In [13]:
pca.explained_variance_ratio_

array([0.99244289])

In [14]:
pca.singular_values_

array([6.30061232])