In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Random Forest --> using many decision trees


In [18]:
from sklearn import datasets

In [20]:
iris= datasets.load_iris()

In [21]:
data= iris

In [22]:
X=iris.data

In [23]:
y=iris.target

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rf= RandomForestClassifier(random_state=0)

In [28]:
# Trained
rf.fit(X,y)

RandomForestClassifier(random_state=0)

In [29]:
# Splitting instead
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.20,random_state=0)

In [40]:
y_pred = rf.predict(X_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [37]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [38]:
# Checking accuracy & confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix

In [42]:
ac=accuracy_score(y_test,y_pred)

In [44]:
print('Accuracy-->',ac)

Accuracy--> 1.0


In [46]:
cf= confusion_matrix(y_test,y_pred)
cf

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]], dtype=int64)