In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
from sklearn.linear_model import LinearRegression

In [6]:
X= np.array([
         [1,1],
         [1,2],
         [2,2],
          [2,3] 
])

In [21]:
y = np.dot(X,np.array([1,2])) + 3

In [22]:
y

array([ 6,  8,  9, 11])

In [23]:
lr= LinearRegression()

In [25]:
# the data is trained 
lr.fit(X,y)

LinearRegression()

In [26]:
lr.predict(np.array([[3,5]]))

array([16.])

In [29]:
data= pd.read_csv("C:\\Users\\Admin\\winequality-red.csv",sep=';')

In [30]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [31]:
lr1= LinearRegression()

In [33]:
X=data.iloc[:,:11] 

In [36]:
y= data.iloc[:,11]

In [37]:
lr1.fit(X,y)

LinearRegression()

In [39]:
lr1.predict(X)

array([5.03285045, 5.13787975, 5.20989474, ..., 5.94304255, 5.47075621,
       6.00819633])

In [40]:
# which is very bad
lr1.score(X,y)

0.3605517030386881