In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [5]:
n_samples,n_features= 10,5

In [6]:
r= np.random.RandomState(0)

In [9]:
y= r.randn(n_samples)

In [10]:
X= r.randn(n_samples,n_features)

In [12]:
y

array([-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614,
       -0.40178094, -1.63019835,  0.46278226, -0.90729836,  0.0519454 ])

In [13]:
model= make_pipeline(StandardScaler(),SVR())

In [14]:
# training model
model.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svr', SVR())])

In [15]:
# prediction
model.predict(X)

array([-0.69483397, -0.45911353, -0.71280646, -1.18573159,  0.07691356,
       -0.49843755, -1.53045841,  0.29576224, -0.80695854, -0.04840118])

In [17]:
y

array([-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614,
       -0.40178094, -1.63019835,  0.46278226, -0.90729836,  0.0519454 ])