In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [7]:
# Support Vectors
# Kernel Functions---> tranforms input features --> higher ddimensional planes & then seprates it
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC

In [8]:
# Input
X=np.array([
    [-1,1],
    [-2,-1],
    [1,1],
    [2,1]
    ])

In [9]:
# Output
y=np.array([1,1,2,2])

In [11]:
# object of SVC
sv= make_pipeline(StandardScaler(),SVC(gamma='auto'))
# whichever Data will be there it will be scaled first & then SVC will be applied

In [12]:
sv.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [17]:
sv.predict([[-2,1]])

array([1])

In [18]:
from sklearn.datasets import load_iris

In [19]:
X,y= load_iris(return_X_y=True)

In [20]:
sv1= make_pipeline(StandardScaler(),SVC(gamma='auto'))

In [21]:
sv1.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [22]:
X[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [25]:
sv1.predict(X[130:133])

array([2, 2, 2])